### PR TITLE
Io support rebased

### PR DESCRIPTION
**Pull request by npd26**

### CODE REVIEW

**Comment by npd26** [comment]
@gavanderhoorn to control gripper from this I/O message, will it required to change anything on controller side? I have changed motoman_driver package on PC according to this. but still I am not getting I/O services.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn to control gripper from this I/O message, will it required to change anything on controller side? 

No, nothing needs to change on the controller.

> I have changed motoman_driver package on PC according to this. but still I am not getting I/O services.

Probably because you have a single-group setup and [these lines](https://github.com/npd26/motoman/pull/1/commits/9e80dd8344db663dcd7c18f76fd404a81a5cd6e5#diff-a99f5449c5369b017cba549fc88643c2R92) only get executed for multi-group configurations.

You'll have to move / copy them to the single-group ctor.

**Comment by npd26** [comment]
yes I have single group setup with DX100. 

`You'll have to move / copy them to the single-group ctor`

could you explain little more as I did not understand what to do?

I am using this package, [https://github.com/gavanderhoorn/motoman/tree/io_support_rebased](url)

**Comment by gavanderhoorn** [comment]
> > You'll have to move / copy them to the single-group ctor
> 
> could you explain little more as I did not understand what to do?

You probably need to move [these lines](https://github.com/gavanderhoorn/motoman/blob/9e80dd8344db663dcd7c18f76fd404a81a5cd6e5/motoman_driver/src/joint_trajectory_streamer.cpp#L92-L97) to [this `init(..)` overload](https://github.com/gavanderhoorn/motoman/blob/9e80dd8344db663dcd7c18f76fd404a81a5cd6e5/motoman_driver/src/joint_trajectory_streamer.cpp#L104).

> I am using this package, [https://github.com/gavanderhoorn/motoman/tree/io_support_rebased](url)

Please note: that branch is very much out-of-date.

**Comment by npd26** [comment]
thank you now I can see that services.

> that branch is very much out-of-date.

I found only this method from search to control gripper(pneumatic) with motoman_driver.

**Comment by npd26** [comment]
@gavanderhoorn gripper services are working.  but, I noticed that /robot_enable and /robot_disable service is not showing anymore. what could be the reason? how to add that?

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn gripper services are working. but, I noticed that /robot_enable and /robot_disable service is not showing anymore. what could be the reason?

that is because:

> that branch is very much out-of-date.

it was created before the enable service was added.

> how to add that?

you'd have to rebase / integrate the enable service with the IO changes.

**Comment by npd26** [comment]
> you'd have to rebase / integrate the enable service with the IO changes

sorry I do not understand. is there another branch that I have to merge or? like above gripper service we added earlier?

**Comment by gavanderhoorn** [comment]
yes, you'll have to 'transplant' the changes that add the io services onto the version that has the enable/disable service.

**Comment by npd26** [comment]
It is working. thank you.

**Pull request closed without merging**
